### ISSUE TITLE
Config to disable velocity-induced screen shake

### ISSUE THREAD

**Issue by LordEnder-Kitty** [Octo-Studios/perception#2]
I realized that when using the Do A Barrel Roll mod, the camera shake when flying at high speeds makes it really difficult to control. There's pretty much a config to change everything in the mod except for that. It would be nice to be able to disable or at least lower the intensity of it.

**Comment by SSKirillSS** [comment]
Done! https://github.com/Octo-Studios/perception/commit/3bfeac7c5efa9a65ae5068c0ca4d3284ba4e3482

Will be released after the full tests.
