### ISSUE TITLE
Make it FOSS

### ISSUE THREAD

**Issue by souldbminersmwc** [Octo-Studios/perception#3]

**Comment by SSKirillSS** [comment]
What exactly do you want from FOSS in this regard? Perception, by its very nature, is a demonstration of the visual features we are developing for the API library of our modding ecosystem. You are also welcome to use this API as a dependency for your own projects if you wish, but I must warn you upfront that these APIs often undergo fundamental changes, so in that case, you'll need to adapt to all these changes. As for a more open license allowing copying and re-releasing, that is not in our interests.

**Comment by souldbminersmwc** [comment]
[Reasoning: Open source](https://opensource.google/documentation/reference/why/)

**Comment by SSKirillSS** [comment]
I think there's nothing else I can do right now. If there are any updates regarding the policy or license, I'll let you know.
