### ISSUE TITLE
Add configs

### ISSUE THREAD

**Issue by Real-Septicake** [Octo-Studios/perception#5]
Give the user some agency in how extreme the effects are. As it stands, some users (myself included) get extremely dizzy as a result of the explosion shake, but still enjoy other aspects of the mod, so giving us a way to possibly lower or disable the strength of the screen shake would be an extremely appreciated addition.

**Comment by SSKirillSS** [comment]
Hello. Configs are already implemented. Look at your config folder, especially a perception.yaml. When extended configs will be activated, after the game restart there will be perception folder where you can configure everything.
